
MODULE tables

	REAL(KIND=8),DIMENSION(:),  ALLOCATABLE	:: PD_now
	
	!! Parameters stripped from tables which are needed for
	!! All collision species. 

	!! HeO
	REAL(KIND=8),DIMENSION(:,:),ALLOCATABLE	:: F_PD_HeO
	REAL(KIND=8),DIMENSION(:),  ALLOCATABLE	:: F_ENERGY_HeO
	REAL(KIND=8),DIMENSION(:),  ALLOCATABLE	:: F_ANGLE_HeO
	REAL(KIND=8),DIMENSION(:),  ALLOCATABLE	:: SP_Y2_HeO 

	INTEGER			:: NUM_EN_HeO
	INTEGER			:: NUM_AN_HeO

	!! HeH
	REAL(KIND=8),DIMENSION(:,:),ALLOCATABLE	:: F_PD_HeH
	REAL(KIND=8),DIMENSION(:),  ALLOCATABLE	:: F_ENERGY_HeH
	REAL(KIND=8),DIMENSION(:),  ALLOCATABLE	:: F_ANGLE_HeH
	REAL(KIND=8),DIMENSION(:),  ALLOCATABLE	:: SP_Y2_HeH

	INTEGER			:: NUM_EN_HeH
	INTEGER			:: NUM_AN_HeH

	!! HeHe
	REAL(KIND=8),DIMENSION(:,:),ALLOCATABLE	:: F_PD_HeHe
	REAL(KIND=8),DIMENSION(:),  ALLOCATABLE	:: F_ENERGY_HeHe
	REAL(KIND=8),DIMENSION(:),  ALLOCATABLE	:: F_ANGLE_HeHe
	REAL(KIND=8),DIMENSION(:),  ALLOCATABLE	:: SP_Y2_HeHe

	INTEGER			:: NUM_EN_HeHe
	INTEGER			:: NUM_AN_HeHe

	!! HH
	REAL(KIND=8),DIMENSION(:,:),ALLOCATABLE	:: F_PD_HH
	REAL(KIND=8),DIMENSION(:),  ALLOCATABLE	:: F_ENERGY_HH
	REAL(KIND=8),DIMENSION(:),  ALLOCATABLE	:: F_ANGLE_HH
	REAL(KIND=8),DIMENSION(:),  ALLOCATABLE	:: SP_Y2_HH

	INTEGER			:: NUM_EN_HH
	INTEGER			:: NUM_AN_HH

	!! SW velocity cumulative probability table
	REAL(KIND=8),DIMENSION(:),  ALLOCATABLE :: Vsw
	REAL(KIND=8),DIMENSION(:),  ALLOCATABLE :: Vsw_Prob
	INTEGER																	:: NUM_Vsw

	!! Mars electron density tables
	REAL(KIND=8),DIMENSION(:), 	ALLOCATABLE	:: electron_den
	REAL(KIND=8),DIMENSION(:), 	ALLOCATABLE	:: electron_alt
	INTEGER																	:: NUM_e_den

	!! H^+ + H elastic tcs tables
	REAL(KIND=8),DIMENSION(:), 	ALLOCATABLE	:: HpH_E
	REAL(KIND=8),DIMENSION(:), 	ALLOCATABLE	:: HpH_tcs
	INTEGER																	:: NUM_HpH_tcs


END MODULE tables


